workflows:
  ios_simulator_react_native:
    name: iOS Simulator Build (React Native, iOS Simulator)
    instance_type: mac_mini_m2
    max_build_duration: 30

    environment:
      node: stable
      
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - ios/Pods
        - node_modules

    scripts: 
      - name: Install Node deps 
        script: | 
          npm install


      - name: Generate native iOS project (Expo prebuild)
        script: |
          set -euo pipefail
          npx expo prebuild --platform ios --non-interactive


      - name: Build .app for iOS Simulator
        script: |
          set -euo pipefail
          cd ios

          echo "Workspaces in ios/:"
          ls *.xcworkspace || echo "No .xcworkspace found"

          # Your Podfile target is `LegalLifelines`, so CocoaPods creates LegalLifelines.xcworkspace
          WORKSPACE="LegalLifelines.xcworkspace"
          SCHEME="LegalLifelines"

          echo "Using workspace: $WORKSPACE"
          echo "Using scheme: $SCHEME"

          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            ARCHS=arm64 \
            ONLY_ACTIVE_ARCH=YES \
            -derivedDataPath build



    artifacts:
      - ios/build/Build/Products/Debug-iphonesimulator/*.app
