workflows:
  ios_simulator_react_native:
    name: iOS Simulator Build (React Native, iOS Simulator)
    instance_type: mac_mini_m2
    max_build_duration: 30

    environment:
      node: stable

    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - node_modules
        # REMOVED: - ios/Pods  <-- THIS WAS CAUSING THE ERROR

    scripts:
      - name: Install Node deps
        script: |
          set -euo pipefail
          npm install

      - name: Generate iOS project (Expo prebuild)
        script: |
          set -euo pipefail
          npx expo prebuild --platform ios --non-interactive

      - name: Install CocoaPods
        script: |
          set -euo pipefail
          cd ios
          # Force clean any cached artifacts
          rm -rf Pods
          rm -rf Podfile.lock
          # Install with repo update to ensure correct arch specs
          pod install --repo-update

      - name: Build .app for iOS Simulator 
        script: |
          set -euo pipefail
          cd ios

          xcodebuild \
            -workspace LegalLifelines.xcworkspace \
            -scheme LegalLifelines \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath ../build \
            -quiet

    artifacts:
      - ios/build/Build/Products/Debug-iphonesimulator/*.app