workflows:
  ios_simulator_react_native:
    name: iOS Simulator Build (React Native, iOS Simulator)
    instance_type: mac_mini_m2
    max_build_duration: 30

    environment:
      node: stable

    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - ios/Pods
        - node_modules

    scripts:
      - name: Install Node deps
        script: |
          set -euo pipefail
          npm install

      - name: Generate iOS project (Expo prebuild)
        script: |
          set -euo pipefail
          npx expo prebuild --platform ios --non-interactive

      - name: Install CocoaPods
        script: |
          set -euo pipefail
          cd ios
          pod install

      - name: Build .app for iOS Simulator 
        script: |
          set -euo pipefail
          cd ios/App

          xcodebuild \
            -workspace LegalLifelines.xcworkspace \
            -scheme LegalLifelines \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath ../build


    artifacts:
      - ios/build/Build/Products/Debug-iphonesimulator/*.app
