workflows:
  ios_simulator_react_native:
    name: iOS Simulator Build (React Native, iOS Simulator)
    instance_type: mac_mini_m2
    max_build_duration: 30

    environment:
      node: stable
      
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - ios/Pods
        - node_modules

    scripts: 
      - name: Install Node deps 
        script: | 
          npm install


      - name: Install CocoaPods
        script: |
          cd ios
          pod install

      - name: Build .app for iOS Simulator
         script: |
          cd ios
          echo "Listing iOS directory:"
          ls

          xcodebuild \
           -workspace LegalLifelines.xcworkspace \
           -scheme LegalLifelines \
           -configuration Debug \
           -sdk iphonesimulator \
           -derivedDataPath build



    artifacts:
      - ios/build/Build/Products/Debug-iphonesimulator/*.app
