workflows:
  ios_simulator_react_native:
    name: iOS Simulator Build (React Native, iOS Simulator)
    instance_type: mac_mini_m2
    max_build_duration: 30

    environment:
      node: stable
      
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - ios/Pods
        - node_modules

    scripts: 
      - name: Install Node deps 
        script: | 
          npm install


      - name: Generate native iOS project (Expo prebuild)
        script: |
          set -euo pipefail
          npx expo prebuild --platform ios --non-interactive

      - name: Install CocoaPods
        script: |
          set -euo pipefail
          cd ios
          pod install
          echo "Contents of ios/ after pod install:"
          ls


      - name: Build .app for iOS Simulator
        script: |
          set -euo pipefail
          cd ios

          xcodebuild \
            -workspace LegalLifelines.xcworkspace \
            -scheme LegalLifelines \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath build



    artifacts:
      - ios/build/Build/Products/Debug-iphonesimulator/*.app
